FROM python:3.8

RUN adduser --disabled-password --gecos "" redactor

RUN mkdir -p /home/app/

WORKDIR /home/app/

RUN chown -R redactor:redactor ./

RUN su - redactor

RUN git clone https://github.com/Evgeny0088/News_redactor.git home/app/

WORKDIR /home/app/News_redactor/app/

