FROM python:3.8

RUN adduser --disabled-password --gecos "" redactor

RUN mkdir -p /home/app/

RUN git clone -b master https://github.com/Evgeny0088/News_redactor.git\
								/home/app/

WORKDIR /home/app/

RUN chown -R redactor:redactor ./

RUN pip install -r /News_redactor/app/requirements.txt

RUN pip install gunicorn

WORKDIR /home/app/News_redactor/app/

RUN chmod +x boot.sh

USER redactor

EXPOSE 5000

ENTRYPOINT ["./boot.sh"]
